FROM ubuntu:24.04

COPY . /rcssserver

RUN apt-get clean && apt-get update --allow-insecure-repositories && \
    DEBIAN_FRONTEND="noninteractive" apt-get -y install \
    tzdata \
    gcc \
    g++ \
    wget \
    libfl-dev \
    flex \
    bison \
    libboost-all-dev \
    automake \
    make \
    cmake \
    iputils-ping \
    build-essential \
    libtool \
    fuse \
    libfuse-dev

RUN cd /rcssserver && ./utils/appimage/build_code.sh