name: ci

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

env:
  BASE_IMAGE: sadraiiali/rcssserver
  BASE_TAG: latest
  RELEASE_PREFIX: "rcssserver-"

jobs:
      
  docker:
    runs-on: ubuntu-latest
    name: Build & Push Docker
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Find CMakeLists.txt version
        id: cmake_version
        run: |
          cmake_version=$(grep -oP 'project\(.* VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
          echo "version=${cmake_version}" >> $GITHUB_OUTPUT

      - name: Build and push RCSSServer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./utils/docker/Dockerfile
          push: true
          tags: "${{ env.BASE_IMAGE }}:latest,${{ env.BASE_IMAGE }}:ubuntu-24-${{ steps.cmake_version.outputs.version }}"

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.BASE_IMAGE }}
          readme-filepath: utils/docker/README.md
          short-description: "RoboCup Soccer Simulator Server"

  app-image:
    runs-on: ubuntu-latest
    name: Build AppImage
    steps:
      - uses: actions/checkout@v4

      - name: Create release folder
        run: |
          mkdir -p ${{ github.workspace }}/artifact

      - name: Find CMakeLists.txt version
        id: cmake_version
        run: |
          cmake_version=$(grep -oP 'project\(.* VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
          echo "version=${cmake_version}" >> $GITHUB_OUTPUT
          
      # ------------------------------------------- Ubuntu 20.04 AppImage
      - name: Prepare builder image for 20.04
        run: |
          docker build -t builder-image:2004 -f ./utils/appimage/Dockerfile.builder-2004 .

      - name: Build app image on 20.04
        run: |
          docker run --privileged --name builder-2004 \
            builder-image:2004 /rcssserver/utils/appimage/build_appimage.sh
          docker cp builder-2004:/rcssserver-x86_64.AppImage ${{ github.workspace }}/artifact/rcssserver-${{ steps.cmake_version.outputs.version }}-x86_64.AppImage

      # ------------------------------------------- Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rcssserver-x86_64
          path: ${{ github.workspace }}/artifact/*
          retention-days: 5
        
      - name: Check if there is no release with the same tag
        id: check_release
        run: |
          out=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.cmake_version.outputs.version }})
          echo "release_exists=${out}" >> $GITHUB_OUTPUT


      # ------------------------------------------- Release
      - name: Create Release
        if: ${{ steps.check_release.outputs.release_exists == '404' }}
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/artifact/rcssserver-${{ steps.cmake_version.outputs.version }}-x86_64.AppImage"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "TBD"
          name: "${{ env.RELEASE_PREFIX }}${{ steps.cmake_version.outputs.version }}"
          tag: ${{ steps.cmake_version.outputs.version }}
